apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: Logstash
  name: logstash-PARAM_APPLICATION
spec:
  revisionHistoryLimit: 5
  replicas: 0
  selector:
    app: Logstash
    deploymentconfig: logstash-PARAM_APPLICATION
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      labels:
        app: Logstash
        deploymentconfig: logstash-PARAM_APPLICATION
    spec:
      containers:
      - env:
        - name: KAFKA_TOPIC_NAME
          value: PARAM_TOPIC_NAME
        - name: ELASTICSEARCH_INDEX
          value: PARAM_ELASTIC_INDEX%{+YYYY.MM.dd}
        envFrom:
        - configMapRef:
            name: config-file-logstash-env
        image: tomihararznde/kafka-logstash:latest
        imagePullPolicy: Always
        name: logstash-PARAM_APPLICATION
        ports:
        - containerPort: 5044
          protocol: TCP
        - containerPort: 9600
          protocol: TCP
        resources:
          limits:
            cpu: 900m
            memory: 1280Mi
          requests:
            cpu: 1m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /usr/share/logstash/pipeline/logstash.conf
            name: config
            readOnly: true
            subPath: logstash.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 509
            name: config-file-logstash
          name: config
